const TaskActionTypes = {
    FETCH_TASKS_DATE_START:'FETCH_TASKS_START',
    FETCH_TASKS_DATE_SUCCESS:'FETCH_TASKS_SUCCESS',
    FETCH_TASKS_DATE_FAILURE:'FETCH_TASKS_FAILURE',
    DELETE_TASK_START:'DELETE_TASK_START',
    DELETE_TASK_SUCCESS:'DELETE_TASK_SUCCESS',
    DELETE_TASK_FAILURE:'DELETE_TASK_FAILURE'
};

export default TaskActionTypes;